import type { Content } from './types';

export const contentData: Content[] = [
  {
    id: '1',
    title: 'The Wonders of the Cosmos',
    category: 'Science',
    image: 'https://placehold.co/600x400/77B5FE/F0F8FF.png',
    dataAiHint: 'galaxy nebula',
    content: 'The cosmos is a vast and mysterious expanse, filled with galaxies, stars, and planets. Each celestial body tells a story of cosmic evolution, from the fiery birth of stars in nebulae to the silent dance of galaxies across billions of light-years. Studying the cosmos allows us to understand our place in the universe and the fundamental laws that govern reality. The sheer scale of it all is humbling and inspiring.',
    keywords: ['space', 'galaxy', 'stars', 'universe'],
  },
  {
    id: '2',
    title: 'A Brief History of Ancient Rome',
    category: 'History',
    image: 'https://placehold.co/600x400/77B5FE/F0F8FF.png',
    dataAiHint: 'roman colosseum',
    content: 'Ancient Rome, from its mythical founding in 753 BC to the fall of the Western Empire in 476 AD, shaped Western civilization in profound ways. Its legacy is visible in law, architecture, language, and governance. The Roman Republic and later the Empire saw incredible feats of engineering like aqueducts and the Colosseum, and the rise of influential figures like Julius Caesar and Augustus. Its history is a rich tapestry of conquest, innovation, and culture.',
    keywords: ['rome', 'history', 'empire', 'caesar'],
  },
  {
    id: '3',
    title: 'The Art of Minimalist Design',
    category: 'Art & Design',
    image: 'https://placehold.co/600x400/77B5FE/F0F8FF.png',
    dataAiHint: 'minimalist interior',
    content: 'Minimalism is more than an aesthetic; it\'s a principle of focusing on the essential. In design, this translates to clean lines, a limited color palette, and an emphasis on negative space. The goal of minimalist design is to create something that is both beautiful and functional without being distracting. It strips away the superfluous to reveal the core purpose and beauty of an object or space.',
    keywords: ['minimalism', 'design', 'art', 'aesthetics'],
  },
  {
    id: '4',
    title: 'Exploring the Deep Ocean',
    category: 'Science',
    image: 'https://placehold.co/600x400/77B5FE/F0F8FF.png',
    dataAiHint: 'underwater jellyfish',
    content: 'The deep ocean is one of the last true frontiers on Earth. Below 200 meters, sunlight fades, and a world of unique biodiversity thrives under immense pressure and in complete darkness. Hydrothermal vents support entire ecosystems, and bioluminescent creatures create their own light. Exploring these depths reveals new species and provides insights into the origins of life on our planet.',
    keywords: ['ocean', 'marine biology', 'deep sea', 'exploration'],
  },
  {
    id: '5',
    title: 'Fundamentals of Machine Learning',
    category: 'Technology',
    image: 'https://placehold.co/600x400/77B5FE/F0F8FF.png',
    dataAiHint: 'abstract code',
    content: 'Machine learning, a subset of artificial intelligence, involves creating algorithms that allow computers to learn from and make predictions or decisions based on data. Key concepts include supervised, unsupervised, and reinforcement learning. From spam filters to recommendation engines, machine learning is a transformative technology that is reshaping industries and our daily lives.',
    keywords: ['ai', 'machine learning', 'data', 'algorithms'],
  },
  {
    id: '6',
    title: 'The Renaissance: A Cultural Rebirth',
    category: 'History',
    image: 'https://placehold.co/600x400/77B5FE/F0F8FF.png',
    dataAiHint: 'renaissance painting',
    content: 'The Renaissance was a fervent period of European cultural, artistic, political and economic “rebirth” following the Middle Ages. Generally described as taking place from the 14th century to the 17th century, the Renaissance promoted the rediscovery of classical philosophy, literature, and art. Some of the greatest thinkers, authors, statesmen, scientists and artists in human history thrived during this era, including Leonardo da Vinci and Michelangelo.',
    keywords: ['renaissance', 'art', 'history', 'europe'],
  },
  {
    id: '7',
    title: 'The Psychology of Color',
    category: 'Art & Design',
    image: 'https://placehold.co/600x400/77B5FE/F0F8FF.png',
    dataAiHint: 'color paint',
    content: 'Color psychology is the study of hues as a determinant of human behavior. Color influences perceptions that are not obvious, such as the taste of food. Colors can have a powerful impact on our mood, emotions, and even physical well-being. For example, blue is often associated with calmness and serenity, while red can evoke strong emotions of passion or anger.',
    keywords: ['color', 'psychology', 'design', 'emotions'],
  },
  {
    id: '8',
    title: 'Quantum Computing Explained',
    category: 'Technology',
    image: 'https://placehold.co/600x400/77B5FE/F0F8FF.png',
    dataAiHint: 'quantum computer',
    content: 'Quantum computing is a revolutionary type of computing that leverages the principles of quantum mechanics, such as superposition and entanglement, to process information. Unlike classical computers that use bits, quantum computers use qubits. This allows them to perform complex calculations at speeds unattainable by classical computers, promising breakthroughs in fields like medicine, materials science, and artificial intelligence.',
    keywords: ['quantum', 'computing', 'technology', 'qubit'],
  },
];
